### ISSUE TITLE
Waybar not loading

### ISSUE THREAD

**Issue by saffanalvy** [arcolinuxb/arco-hyprland#1]
Hi.
Today, I have freshly downloaded and installed the ArcolinuxB Hyprland v23.05.04 ISO.
However, after the install Waybar is not loading.
When I run waybar from the shell it says,
`waybar: error while loading shared libraries: libfmt.so.9: cannot open shared object file: No such file or directory`
This happens out of the box, just booting after fresh install.
I don't know much but what I've understood that the waybar config and hyprland config files are okay.
Any suggestions or fix?
Thanks.

**Comment by saffanalvy** [comment]
So, apparently, some libraries were missing.
I just uninstalled Waybar-Hyprland `sudo pacman -R waybar-hyprland-git` and installed Waybar `sudo pacman -Syu waybar` and it solved the issue for me. Now the Waybar is loading with Arcolinux config.

**Comment by saffanalvy** [comment]
So, apparently, some libraries were missing.
I just uninstalled Waybar-Hyprland `sudo pacman -R waybar-hyprland-git` and installed Waybar `sudo pacman -Syu waybar` and it solved the issue for me. Now the Waybar is loading with Arcolinux config.

**Comment by arcolinuxz** [comment]
for future reference for readers
anything fails
update your system and build the failing package with yay or paru from AUR

**Comment by arcolinuxz** [comment]
solved now
